In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [6]:
df=pd.read_csv('E://Food-Demand-Forecasting-Major//dataset//food_Demand_test.csv')
df.head(10)

id  week  center_id  meal_id  checkout_price  base_price  \
0  1028232   146         55     1885          158.11      159.11   
1  1127204   146         55     1993          160.11      159.11   
2  1212707   146         55     2539          157.14      159.14   
3  1082698   146         55     2631          162.02      162.02   
4  1400926   146         55     1248          163.93      163.93   
5  1284113   146         55     1778          190.15      190.15   
6  1197966   146         55     1062          191.09      192.09   
7  1132739   146         55     2707          242.56      240.56   
8  1057981   146         55     1207          360.90      360.90   
9  1095932   146         55     1230          383.18      384.18   

   emailer_for_promotion  homepage_featured  
0                      0                  0  
1                      0                  0  
2                      0                  0  
3                      0                  0  
4                      0                  0  
5                      0                  0  
6                      0                  0  
7                      0                  0  
8                      0                  0  
9                      0                  0

In [15]:
df.tail(10)

id  week  center_id  meal_id  checkout_price  base_price  \
32563  1001148   155         61     2867          678.03      679.03   
32564  1169203   155         61     2760          243.50      243.50   
32565  1389523   155         61     1525          320.13      319.13   
32566  1304998   155         61     2704          321.13      321.13   
32567  1462767   155         61     2492          456.93      456.93   
32568  1250239   155         61     1543          482.09      484.09   
32569  1039516   155         61     2304          483.09      483.09   
32570  1158107   155         61     2664          322.07      323.07   
32571  1444235   155         61     2569          322.07      323.07   
32572  1291286   155         61     2490          276.45      276.45   

       emailer_for_promotion  homepage_featured  
32563                      0                  0  
32564                      0                  0  
32565                      0                  0  
32566                      0                  0  
32567                      0                  0  
32568                      0                  0  
32569                      0                  0  
32570                      0                  0  
32571                      0                  0  
32572                      0                  0

In [21]:
df.sample(10)

id  week  center_id  meal_id  checkout_price  base_price  \
5438   1489537   147         67     2104          639.23      641.23   
5818   1210842   147        143     2290          298.79      297.79   
13666  1004841   150         57     1543          483.09      483.09   
23572  1085401   153        152     1962          508.34      508.34   
21688  1255164   152        145     1248           98.00      147.44   
26553  1221066   154         93     2826          325.92      325.92   
17669  1430511   151        162     1230          333.68      335.68   
13723  1175889   150         89     2104          581.03      581.03   
20807  1050747   152        126     1754          193.03      327.86   
19088  1084025   151         10     1311          170.75      191.15   

       emailer_for_promotion  homepage_featured  
5438                       0                  0  
5818                       0                  0  
13666                      0                  0  
23572                      0                  0  
21688                      0                  0  
26553                      0                  0  
17669                      0                  0  
13723                      0                  0  
20807                      1                  1  
19088                      0                  0

In [26]:
a=df['center_id'].unique()
a

array([ 55,  24,  11,  83,  32,  13, 109,  52,  93, 186, 146,  57, 149,
        89, 124, 152,  97,  74, 108,  99,  66,  94,  91,  20,  34, 137,
        92, 126,  36, 162,  75, 177,  27, 157, 106,  64, 129,  14,  17,
       153, 139, 161,  81,  26,  73,  50, 104,  42, 113, 145,  53,  72,
        67, 174,  29,  77,  41,  30,  76,  59,  88, 143,  58,  10, 101,
        80,  43,  65,  39, 102, 110, 132,  23,  86,  68,  51,  61])

In [30]:
df['emailer_for_promotion'].unique()

array([0, 1])

In [31]:
df['homepage_featured'].unique()

array([0, 1])

In [29]:
df['meal_id'].unique()

array([1885, 1993, 2539, 2631, 1248, 1778, 1062, 2707, 1207, 1230, 2322,
       2290, 1727, 1109, 2577, 2640, 2826, 1754, 1971, 1198, 1311, 1803,
       1558, 2581, 1962, 2444, 2867, 1525, 2704, 2492, 1543, 2304, 2664,
       2569, 2490, 2139, 1571, 2956, 1878, 2306, 1216, 2126, 1902, 1770,
       1438, 2494, 1847, 1445, 2760, 1247, 2104])

In [28]:
a.sort()
a

array([ 10,  11,  13,  14,  17,  20,  23,  24,  26,  27,  29,  30,  32,
        34,  36,  39,  41,  42,  43,  50,  51,  52,  53,  55,  57,  58,
        59,  61,  64,  65,  66,  67,  68,  72,  73,  74,  75,  76,  77,
        80,  81,  83,  86,  88,  89,  91,  92,  93,  94,  97,  99, 101,
       102, 104, 106, 108, 109, 110, 113, 124, 126, 129, 132, 137, 139,
       143, 145, 146, 149, 152, 153, 157, 161, 162, 174, 177, 186])

In [23]:
df['week'].unique()

array([146, 147, 148, 149, 150, 151, 152, 153, 154, 155])

In [10]:
df.describe()

id          week     center_id       meal_id  checkout_price  \
count  3.257300e+04  32573.000000  32573.000000  32573.000000    32573.000000   
mean   1.248476e+06    150.477819     81.901728   2032.067909      341.854440   
std    1.441580e+05      2.864072     45.950455    547.199004      153.893886   
min    1.000085e+06    146.000000     10.000000   1062.000000       67.900000   
25%    1.123969e+06    148.000000     43.000000   1558.000000      214.430000   
50%    1.247296e+06    150.000000     76.000000   1993.000000      320.130000   
75%    1.372971e+06    153.000000    110.000000   2569.000000      446.230000   
max    1.499996e+06    155.000000    186.000000   2956.000000     1113.620000   

         base_price  emailer_for_promotion  homepage_featured  
count  32573.000000           32573.000000       32573.000000  
mean     356.493615               0.066435           0.081356  
std      155.150101               0.249045           0.273385  
min       89.240000               0.000000           0.000000  
25%      243.500000               0.000000           0.000000  
50%      321.130000               0.000000           0.000000  
75%      455.930000               0.000000           0.000000  
max     1112.620000               1.000000           1.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32573 entries, 0 to 32572
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     32573 non-null  int64  
 1   week                   32573 non-null  int64  
 2   center_id              32573 non-null  int64  
 3   meal_id                32573 non-null  int64  
 4   checkout_price         32573 non-null  float64
 5   base_price             32573 non-null  float64
 6   emailer_for_promotion  32573 non-null  int64  
 7   homepage_featured      32573 non-null  int64  
dtypes: float64(2), int64(6)
memory usage: 2.0 MB


In [12]:
df.shape

(32573, 8)

In [14]:
df.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
dtype: int64

In [32]:
sns.boxplot(x='',y='',data=df)

ValueError: Could not interpret value `` for `x`. An entry with this name does not appear in `data`.

In [33]:
df.corr()

id      week  center_id   meal_id  \
id                     1.000000  0.011176   0.008868 -0.002242   
week                   0.011176  1.000000  -0.001295  0.003320   
center_id              0.008868 -0.001295   1.000000  0.008715   
meal_id               -0.002242  0.003320   0.008715  1.000000   
checkout_price        -0.012404  0.014100  -0.002326  0.043286   
base_price            -0.010621 -0.012672  -0.005593  0.031053   
emailer_for_promotion  0.000697 -0.028666   0.008064 -0.032147   
homepage_featured     -0.002035 -0.039336  -0.005855  0.002107   

                       checkout_price  base_price  emailer_for_promotion  \
id                          -0.012404   -0.010621               0.000697   
week                         0.014100   -0.012672              -0.028666   
center_id                   -0.002326   -0.005593               0.008064   
meal_id                      0.043286    0.031053              -0.032147   
checkout_price               1.000000    0.967567               0.026338   
base_price                   0.967567    1.000000               0.179885   
emailer_for_promotion        0.026338    0.179885               1.000000   
homepage_featured           -0.048799    0.043210               0.460819   

                       homepage_featured  
id                             -0.002035  
week                           -0.039336  
center_id                      -0.005855  
meal_id                         0.002107  
checkout_price                 -0.048799  
base_price                      0.043210  
emailer_for_promotion           0.460819  
homepage_featured               1.000000

In [34]:

y=df['checkout_price']
y.head()

0    158.11
1    160.11
2    157.14
3    162.02
4    163.93
Name: checkout_price, dtype: float64

In [35]:
x=df

In [36]:
x.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1028232   146         55     1885          158.11      159.11   
1  1127204   146         55     1993          160.11      159.11   
2  1212707   146         55     2539          157.14      159.14   
3  1082698   146         55     2631          162.02      162.02   
4  1400926   146         55     1248          163.93      163.93   

   emailer_for_promotion  homepage_featured  
0                      0                  0  
1                      0                  0  
2                      0                  0  
3                      0                  0  
4                      0                  0

In [42]:
x.drop('checkout_price',axis=1,inplace=True)

In [43]:
x.head()

id  week  center_id  meal_id  base_price  emailer_for_promotion  \
0  1028232   146         55     1885      159.11                      0   
1  1127204   146         55     1993      159.11                      0   
2  1212707   146         55     2539      159.14                      0   
3  1082698   146         55     2631      162.02                      0   
4  1400926   146         55     1248      163.93                      0   

   homepage_featured  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0

In [44]:
df.nunique()

id                       32573
week                        10
center_id                   77
meal_id                     51
base_price                1179
emailer_for_promotion        2
homepage_featured            2
dtype: int64

In [45]:
df.drop('id',axis=1)

week  center_id  meal_id  base_price  emailer_for_promotion  \
0       146         55     1885      159.11                      0   
1       146         55     1993      159.11                      0   
2       146         55     2539      159.14                      0   
3       146         55     2631      162.02                      0   
4       146         55     1248      163.93                      0   
...     ...        ...      ...         ...                    ...   
32568   155         61     1543      484.09                      0   
32569   155         61     2304      483.09                      0   
32570   155         61     2664      323.07                      0   
32571   155         61     2569      323.07                      0   
32572   155         61     2490      276.45                      0   

       homepage_featured  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0  
...                  ...  
32568                  0  
32569                  0  
32570                  0  
32571                  0  
32572                  0  

[32573 rows x 6 columns]

In [47]:
x.drop('id',axis=1)

week  center_id  meal_id  base_price  emailer_for_promotion  \
0       146         55     1885      159.11                      0   
1       146         55     1993      159.11                      0   
2       146         55     2539      159.14                      0   
3       146         55     2631      162.02                      0   
4       146         55     1248      163.93                      0   
...     ...        ...      ...         ...                    ...   
32568   155         61     1543      484.09                      0   
32569   155         61     2304      483.09                      0   
32570   155         61     2664      323.07                      0   
32571   155         61     2569      323.07                      0   
32572   155         61     2490      276.45                      0   

       homepage_featured  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0  
...                  ...  
32568                  0  
32569                  0  
32570                  0  
32571                  0  
32572                  0  

[32573 rows x 6 columns]

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [57]:
print(len(x_train))
print(len(x_test))

26058
6515


In [58]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [59]:
y_predict=LR.predict(x_test)

In [60]:
y_predict

array([163.13881272, 180.20250054, 230.62366225, ..., 248.5032722 ,
       466.45738102, 499.87310301])

In [61]:
from sklearn.metrics import (root_mean_squared_error,mean_squared_error,r2_score,mean_absolute_error)
r2_score=r2_score(y_test,y_predict)

In [62]:
r2_score

0.9517155938369393

In [63]:
MSE=mean_squared_error(y_test,y_predict)
MSE

1115.2695330709148

In [64]:
RMSE=root_mean_squared_error(y_test,y_predict)
RMSE

33.39565140959096

In [65]:
MAE=mean_absolute_error(y_test,y_predict)
MAE

17.21326469820289

In [68]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(LR,x,y,cv=5,scoring='r2')
scores.mean()

np.float64(0.941629021007282)

In [69]:
float(scores.mean())

0.941629021007282